//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemNet.Practice.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemNet.Practice.Common.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Deny.
        /// </summary>
        public static string AccessDeny {
            get {
                return ResourceManager.GetString("AccessDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Funcionality needs at least one event registered.
        /// </summary>
        public static string AtleastOneEvent {
            get {
                return ResourceManager.GetString("AtleastOneEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Profile needs at least one funcionality registered.
        /// </summary>
        public static string AtleastOneFuncionality {
            get {
                return ResourceManager.GetString("AtleastOneFuncionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked user, Contact adminstrator of system..
        /// </summary>
        public static string BlockedUser {
            get {
                return ResourceManager.GetString("BlockedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congreagation is required.
        /// </summary>
        public static string CongreagationRequired {
            get {
                return ResourceManager.GetString("CongreagationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email already exists.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The E-mail is Invalid.
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail secundary must be diferent from the primary e-mail.
        /// </summary>
        public static string EmailMustBeDiferent {
            get {
                return ResourceManager.GetString("EmailMustBeDiferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date must be greater than the start date.
        /// </summary>
        public static string EndDateGreater {
            get {
                return ResourceManager.GetString("EndDateGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists.
        /// </summary>
        public static string Exists {
            get {
                return ResourceManager.GetString("Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expiration date must be greater or equal than the initial date.
        /// </summary>
        public static string ExpirationDateGrantInitialDate {
            get {
                return ResourceManager.GetString("ExpirationDateGrantInitialDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Funcionality / Event {0} does not exist.
        /// </summary>
        public static string FuncionalityDoesNotExists {
            get {
                return ResourceManager.GetString("FuncionalityDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Funcionality &apos;{0}&apos; already exist for this profile.
        /// </summary>
        public static string FuncionalityDuplicate {
            get {
                return ResourceManager.GetString("FuncionalityDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group is required.
        /// </summary>
        public static string GroupRequired {
            get {
                return ResourceManager.GetString("GroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}! A new account has been created for you in the System..
        /// </summary>
        public static string HtmlBody_1 {
            get {
                return ResourceManager.GetString("HtmlBody_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}! Your user´s password was reset in the system..
        /// </summary>
        public static string HtmlBody_1b {
            get {
                return ResourceManager.GetString("HtmlBody_1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        public static string HtmlBody_2 {
            get {
                return ResourceManager.GetString("HtmlBody_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Password:.
        /// </summary>
        public static string HtmlBody_3 {
            get {
                return ResourceManager.GetString("HtmlBody_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upon entrance for your safety, prompted the change this password..
        /// </summary>
        public static string HtmlBody_4 {
            get {
                return ResourceManager.GetString("HtmlBody_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &lt;a href=&quot;{0}&quot;&gt;here&lt;/a&gt; to connect in the system..
        /// </summary>
        public static string HtmlBody_5 {
            get {
                return ResourceManager.GetString("HtmlBody_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial date must be greater or equal than the current date.
        /// </summary>
        public static string InitialDateGrantCurrentDate {
            get {
                return ResourceManager.GetString("InitialDateGrantCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credentials.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is invalid..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader is required.
        /// </summary>
        public static string LeaderRequired {
            get {
                return ResourceManager.GetString("LeaderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This login or E-mail already exists.
        /// </summary>
        public static string LoginExists {
            get {
                return ResourceManager.GetString("LoginExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not have more than {1} chars.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login should not have more than {0} chars.
        /// </summary>
        public static string MaxEmail {
            get {
                return ResourceManager.GetString("MaxEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login should not have more than {0} chars.
        /// </summary>
        public static string MaxLogin {
            get {
                return ResourceManager.GetString("MaxLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name should not have more than {0} chars.
        /// </summary>
        public static string MaxName {
            get {
                return ResourceManager.GetString("MaxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should not have more than {0} chars.
        /// </summary>
        public static string MaxPassword {
            get {
                return ResourceManager.GetString("MaxPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number should not have more than {0} chars.
        /// </summary>
        public static string MaxPhone {
            get {
                return ResourceManager.GetString("MaxPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should have at least {1} chars.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login should have at least {0} chars.
        /// </summary>
        public static string MinLogin {
            get {
                return ResourceManager.GetString("MinLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name should have at least {0} chars.
        /// </summary>
        public static string MinName {
            get {
                return ResourceManager.GetString("MinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should have at least {0} chars.
        /// </summary>
        public static string MinPassword {
            get {
                return ResourceManager.GetString("MinPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name already exists.
        /// </summary>
        public static string NameExists {
            get {
                return ResourceManager.GetString("NameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password can&apos;t not be equal the previous password.
        /// </summary>
        public static string NewPasswordEqualPrevious {
            get {
                return ResourceManager.GetString("NewPasswordEqualPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When informing an operator group, the operator, customer or room should not be informed..
        /// </summary>
        public static string OperatorGroupInvalid {
            get {
                return ResourceManager.GetString("OperatorGroupInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords does not match..
        /// </summary>
        public static string PasswordDoesNotMatch {
            get {
                return ResourceManager.GetString("PasswordDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The period of the system access has expired. Contact the administrator of the operator..
        /// </summary>
        public static string PeriodoInvalid {
            get {
                return ResourceManager.GetString("PeriodoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Funcionality / event {0} already exists.
        /// </summary>
        public static string ProfileEventAlreadyExists {
            get {
                return ResourceManager.GetString("ProfileEventAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This profile &apos;{0}&apos; has associate user(s). .
        /// </summary>
        public static string ProfileHasUsers {
            get {
                return ResourceManager.GetString("ProfileHasUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile is required.
        /// </summary>
        public static string ProfileRequired {
            get {
                return ResourceManager.GetString("ProfileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found.
        /// </summary>
        public static string RegisterNotFound {
            get {
                return ResourceManager.GetString("RegisterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain letters and numbers and at least one capital letter..
        /// </summary>
        public static string RequirementsPassword {
            get {
                return ResourceManager.GetString("RequirementsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible is required.
        /// </summary>
        public static string ResponsibleRequired {
            get {
                return ResourceManager.GetString("ResponsibleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Sex is invalid.
        /// </summary>
        public static string SexInvalid {
            get {
                return ResourceManager.GetString("SexInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account Created .
        /// </summary>
        public static string SubjectEmail {
            get {
                return ResourceManager.GetString("SubjectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account was reset .
        /// </summary>
        public static string SubjectEmail1 {
            get {
                return ResourceManager.GetString("SubjectEmail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This System does not exists.
        /// </summary>
        public static string SystemDoesNotExists {
            get {
                return ResourceManager.GetString("SystemDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System is required.
        /// </summary>
        public static string SystemRequired {
            get {
                return ResourceManager.GetString("SystemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Operator should be informed.
        /// </summary>
        public static string TellOperator {
            get {
                return ResourceManager.GetString("TellOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login / Pass invalid..
        /// </summary>
        public static string UserPassInvalidValidator {
            get {
                return ResourceManager.GetString("UserPassInvalidValidator", resourceCulture);
            }
        }
    }
}
